name: Test & Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run tests
      - name: Run primary tests
        run: npm test

      # Step 5: Mock additional tests
      - name: Run API test
        run: echo "Running mock API test..." && exit 0
      - name: Run UI test
        run: echo "Running mock UI test..." && exit 0

      # Step 6: Build the project
      - name: Build project
        run: npm run build

      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      # Step 8: Report Build Status
      - name: Report build status
        run: echo "Build and deployment successful!"

      # Step 9: Provide deployment link
      - name: Deployment Link
        run: |
          echo "Your application has been deployed!"
          echo "Visit: https://abdu1964.github.io/book_reservation1/"
