name: Test & Deploy Workflow

on:
  push:           # Trigger on every push
  pull_request:   # Trigger on every pull request

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: '18' # Use stable Node.js version
          cache: "npm"

      - name: Install dependencies
        run: npm ci # Clean install for CI environments

      - name: Run tests
        run: npm test # Runs your test suite

      - name: Lint codebase
        run: npm run lint # Ensure this script is defined in your package.json

      - name: Check for vulnerabilities
        run: npm audit --production # Optional: Security scan of dependencies

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: test # Ensures 'deploy' only runs if 'test' succeeds

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: '18'
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build # Ensure 'build' script exists in package.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # Adjust if your build output directory is different !
